#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/flightapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: QWE123asd
#    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://jiayan-flightdb.cj6gcogsidzt.ap-southeast-2.rds.amazonaws.com:3306/flight_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8
    username: admin
    password: QWE123asd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate    #update:自动创建/更新表结构，不删除数据（开发时常用 )
    show-sql: true
  sql:
    init:
      mode: never   # never: 启动时不执行 schema.sql 和 data.sql。always 始终执行初始化 SQL 脚本（无论是否为内存数据库） 开发可用

#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor.sql.BasicBinder: trace

  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8080

app:
  jwt:
    secret: YmFzZTY0ZW5jb2RlZHNlY3JldGtleWZvcnRlc3Rpbmc=    #用Base64 编码的密钥, 更安全
    expiration-ms: 1800000   # 30分钟，建议10-30分钟之内