spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flightapi?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: QWE123asd
    driver-class-name: com.mysql.cj.jdbc.Driver
